# Generated by Django 3.2.3 on 2025-02-11 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20250211_0113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagInRecipe',
        ),
    ]
