# Generated by Django 3.2.3 on 2025-02-11 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_delete_taginrecipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
