# Generated by Django 4.2.11 on 2025-02-12 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_favorite_unique_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(upload_to='recipes/', verbose_name='Фотография рецепта'),
        ),
    ]
