# Generated by Django 3.2.3 on 2025-02-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='bio',
        ),
        migrations.AddField(
            model_name='apiuser',
            name='avatar',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='apiuser',
            name='is_subscribed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='confirmation_code',
            field=models.SmallIntegerField(default=8285, verbose_name='код'),
        ),
    ]
