# Generated by Django 3.2.3 on 2025-02-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250203_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='confirmation_code',
            field=models.SmallIntegerField(default=4067, verbose_name='код'),
        ),
    ]
