# Generated by Django 3.2.3 on 2025-02-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_apiuser_confirmation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='bio',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='confirmation_code',
            field=models.SmallIntegerField(default=3026, verbose_name='код'),
        ),
    ]
