# Generated by Django 3.2.3 on 2025-02-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20250203_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='apiuser',
            name='confirmation_code',
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user/avatars/'),
        ),
        migrations.AlterField(
            model_name='apiuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
