# Generated by Django 3.2.3 on 2025-02-04 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20250204_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='avatar',
        ),
    ]
