# Generated by Django 3.2.3 on 2025-02-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_apiuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='user/avatars/'),
        ),
    ]
