# Generated by Django 3.2.3 on 2025-02-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_apiuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, verbose_name='пароль'),
        ),
    ]
