# Generated by Django 3.2.3 on 2025-02-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20250207_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiuser',
            name='is_subscribed',
        ),
    ]
