# Generated by Django 3.2.3 on 2025-02-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_apiuser_is_subscribed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiuser',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'Пользователь'), ('admin', 'Админ')], default='user', max_length=10, verbose_name='роль'),
        ),
    ]
